In [1]:
import numpy as np
import matplotlib.pyplot as plt

# 1. Genera un array de NumPy con valores desde 10 hasta 29
arr1 = np.arange(10, 30)
print("Array de 10 a 29:", arr1)

# 2. Suma de todos los elementos en un array de 10x10 lleno de unos
arr2 = np.ones((10, 10))
suma_arr2 = np.sum(arr2)
print("Suma de array 10x10 de unos:", suma_arr2)

# 3. Producto elemento a elemento de dos arrays de tamaño 5 con números aleatorios de 1 a 10
np.random.seed(42)  # Para reproducibilidad
arr3_a = np.random.randint(1, 11, size=5)
arr3_b = np.random.randint(1, 11, size=5)
producto_elemento = arr3_a * arr3_b
print("Array A:", arr3_a)
print("Array B:", arr3_b)
print("Producto elemento a elemento:", producto_elemento)

# 4. Matriz 4x4 con elementos i*j, y su inversa
i, j = np.meshgrid(np.arange(4), np.arange(4), indexing='ij')
matriz_ij = i * j
print("Matriz i*j:\n", matriz_ij)

# Solo si es invertible (determinante != 0)
if np.linalg.det(matriz_ij) != 0:
    inversa = np.linalg.inv(matriz_ij)
    print("Inversa de la matriz:\n", inversa)
else:
    print("La matriz no es invertible.")

# 5. Valores máximo y mínimo en un array de 100 elementos aleatorios + índices
arr5 = np.random.random(100)
max_val = np.max(arr5)
min_val = np.min(arr5)
idx_max = np.argmax(arr5)
idx_min = np.argmin(arr5)
print(f"Máximo: {max_val} en índice {idx_max}")
print(f"Mínimo: {min_val} en índice {idx_min}")

Array de 10 a 29: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
Suma de array 10x10 de unos: 100.0
Array A: [7 4 8 5 7]
Array B: [10  3  7  8  5]
Producto elemento a elemento: [70 12 56 40 35]
Matriz i*j:
 [[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]
La matriz no es invertible.
Máximo: 0.9868869366005173 en índice 61
Mínimo: 0.005522117123602399 en índice 64


In [2]:
# 6. Broadcasting: array 3x1 + array 1x3 → 3x3
arr6_a = np.array([[1], [2], [3]])      # 3x1
arr6_b = np.array([[10, 20, 30]])       # 1x3
resultado_broadcast = arr6_a + arr6_b
print("Resultado broadcasting 3x3:\n", resultado_broadcast)

# 7. Submatriz 2x2 desde la segunda fila y columna (índices 1:3, 1:3)
matriz7 = np.random.randint(1, 100, (5,5))
submatriz = matriz7[1:3, 1:3]
print("Matriz 5x5 original:\n", matriz7)
print("Submatriz 2x2:\n", submatriz)

# 8. Array de ceros de tamaño 10, cambiar índices 3 a 6 a 5
arr8 = np.zeros(10)
arr8[3:7] = 5  # [3,4,5,6] → 4 elementos
print("Array modificado:", arr8)

# 9. Invertir orden de filas de una matriz 3x3
matriz9 = np.array([[1,2,3], [4,5,6], [7,8,9]])
matriz9_invertida = matriz9[::-1]
print("Matriz original:\n", matriz9)
print("Matriz con filas invertidas:\n", matriz9_invertida)

# 10. Seleccionar elementos > 0.5 en array de 10 números aleatorios
arr10 = np.random.random(10)
seleccion = arr10[arr10 > 0.5]
print("Array original:", arr10)
print("Elementos > 0.5:", seleccion)

Resultado broadcasting 3x3:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]
Matriz 5x5 original:
 [[36 13 32 71 59]
 [86 28 66 42 45]
 [62 57  6 28 28]
 [44 84 30 62 75]
 [92 89 62 97  1]]
Submatriz 2x2:
 [[28 66]
 [57  6]]
Array modificado: [0. 0. 0. 5. 5. 5. 5. 0. 0. 0.]
Matriz original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriz con filas invertidas:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Array original: [0.22793516 0.42710779 0.81801477 0.86073058 0.00695213 0.5107473
 0.417411   0.22210781 0.11986537 0.33761517]
Elementos > 0.5: [0.81801477 0.86073058 0.5107473 ]
